run:
  timeout: 10m
  build-tags:
    - edgex
  go: '1.22'

issues:
  exclude-dirs:
    - internal/plugin/wasm
    - extensions/functions/tfLite
    - extensions/functions/labelImage
    - internal/pkg/httpx/httptestx

linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - govet
    - staticcheck
    - misspell
    - unconvert
    - usestdlibvars

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/lf-edge/ekuiper)