run:
  timeout: 10m
  build-tags:
    - full
  go: '1.23'

linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - govet
    - staticcheck
    - misspell
    - unconvert
    - usestdlibvars

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/lf-edge/ekuiper/v2)
