# Copyright 2021 EMQ Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.20-alpine AS builder

COPY . /go/kuiper

WORKDIR /go/kuiper/tools/kubernetes

RUN go build -o kuiper-kubernetes-tool main.go

FROM alpine:3.16

WORKDIR /kuiper-kubernetes-tool

RUN mkdir -p log

COPY --from=builder /go/kuiper/tools/kubernetes/kuiper-kubernetes-tool .
COPY --from=builder /go/kuiper/tools/kubernetes/etc etc
COPY --from=builder /go/kuiper/tools/kubernetes/sample sample

CMD ["./kuiper-kubernetes-tool", "etc/cf.yaml"]
