# Copyright 2021-2023 EMQ Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG GO_VERSION=1.23.4
FROM ghcr.io/lf-edge/ekuiper/base:$GO_VERSION-debian AS builder

COPY . /go/kuiper

WORKDIR /go/kuiper

RUN sed -i -r "s|([ \t]*version=).*|\1'$(git describe --tags --always --match 'v[0-9]*.[0-9]*.[0-9]*' | sed 's/^v//g' | sed -E 's/^(.*)-([0-9]+)-.*$/\1a\2/')',|1" sdk/python/setup.py
RUN cat sdk/python/setup.py
RUN make build_with_edgex_and_script

FROM python:3.12-bookworm AS python-builder

COPY --from=builder /go/kuiper/sdk/python /sdk/python
ARG DEBIAN_FRONTEND="noninteractive"

# Install build dependencies for pynng (including nng and mbedtls)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget cmake libffi-dev git \
        build-essential gcc g++ libc-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && python3 -m ensurepip --upgrade \
    && python3 -m pip install --no-cache-dir setuptools

WORKDIR /sdk/python
RUN cat setup.py
RUN pip wheel .

FROM python:3.12-slim-bookworm

COPY --from=python-builder /sdk/python /sdk/python
WORKDIR /sdk/python
RUN pip install *.whl

COPY --from=builder /go/kuiper/_build/kuiper-* /kuiper/
WORKDIR /kuiper
RUN rm -rf /sdk/python
COPY ./deploy/docker/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENV MAINTAINER="emqx.io"
ENV KUIPER_HOME="/kuiper"
ENV KUIPER__BASIC__CONSOLELOG=true

VOLUME ["/kuiper/etc", "/kuiper/data", "/kuiper/plugins", "/kuiper/log"]
EXPOSE 9081 20498

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

CMD ["./bin/kuiperd"]
