# Copyright 2021-2023 EMQ Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG GO_VERSION=1.24.1
FROM ghcr.io/lf-edge/ekuiper/base:$GO_VERSION-debian AS builder

COPY . /go/kuiper

WORKDIR /go/kuiper

RUN make build_with_edgex_and_script

FROM python:3.12-bookworm AS python-builder

COPY ./sdk/python /sdk/python

ARG DEBIAN_FRONTEND="noninteractive"

# Install build dependencies for pynng (including nng and mbedtls)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget cmake libffi-dev git \
        build-essential gcc g++ libc-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && python3 -m ensurepip --upgrade \
    && python3 -m pip install --no-cache-dir setuptools

WORKDIR /sdk/python
RUN python3 setup.py sdist && python3 setup.py install

FROM python:3.12-slim-bookworm

COPY --from=builder /go/kuiper/_build/kuiper-* /kuiper/
COPY --from=python-builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

WORKDIR /kuiper
COPY ./deploy/docker/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENV MAINTAINER="emqx.io"
ENV KUIPER_HOME="/kuiper"
ENV KUIPER__BASIC__CONSOLELOG=true

VOLUME ["/kuiper/etc", "/kuiper/data", "/kuiper/plugins", "/kuiper/log"]
EXPOSE 9081 20498

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

CMD ["./bin/kuiperd"]
