// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "handles root requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Server Information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.information"
                        }
                    }
                }
            },
            "post": {
                "description": "handles root requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Server Information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.information"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.information": {
            "type": "object",
            "properties": {
                "arch": {
                    "description": "Architecture (e.g., amd64, arm)",
                    "type": "string"
                },
                "cpuUsage": {
                    "description": "CPU usage, optional",
                    "type": "string"
                },
                "memoryTotal": {
                    "description": "Total memory",
                    "type": "string"
                },
                "memoryUsed": {
                    "description": "Memory used, optional",
                    "type": "string"
                },
                "os": {
                    "description": "Operating system",
                    "type": "string"
                },
                "upTimeSeconds": {
                    "description": "Uptime in seconds",
                    "type": "integer"
                },
                "version": {
                    "description": "The version of the application",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "eKuiper API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
