###

POST http://127.0.0.1:9081/plugins/sources
Content-Type: application/json

{"name":"random2","file":"http://127.0.0.1/plugins/sources/random2.zip","callback":""}

###
GET http://127.0.0.1:9081/plugins/sources

###
DELETE http://127.0.0.1:9081/plugins/sources/random2

###
POST http://127.0.0.1:9081/plugins/sinks
Content-Type: application/json

{"name":"random2","file":"http://127.0.0.1/plugins/sources/random2.zip"}

###
GET http://127.0.0.1:9081/plugins/sinks

###
DELETE http://127.0.0.1:9081/plugins/sinks/random2?restart=1

###
POST http://127.0.0.1:9081/plugins/functions
Content-Type: application/json

{"name":"random3","file":"https://jbpz.oss-cn-beijing.aliyuncs.com/random3.zip"}

###
GET http://127.0.0.1:9081/plugins/functions

###
DELETE http://127.0.0.1:9081/plugins/functions/random2

###2217