###

POST http://127.0.0.1:9081/plugins/sources
Content-Type: application/json

{"name":"random2","file":"http://127.0.0.1/plugins/sources/random2.zip","callback":""}

###
GET http://127.0.0.1:9081/plugins/sources

###
DELETE http://127.0.0.1:9081/plugins/sources/random2

###
POST http://127.0.0.1:9081/plugins/sinks
Content-Type: application/json

{"name":"random2","file":"http://127.0.0.1/plugins/sources/random2.zip","callback":"http://www.mycallback.com/callback"}

###
GET http://127.0.0.1:9081/plugins/sinks

###
DELETE http://127.0.0.1:9081/plugins/sinks/random2?callback=http%3A%2F%2Fwww.mycallback.com%2Fcallback

###
POST http://127.0.0.1:9081/plugins/functions
Content-Type: application/json

{"name":"random2","file":"http://127.0.0.1/plugins/sources/random2.zip","callback":""}

###
GET http://127.0.0.1:9081/plugins/functions

###
DELETE http://127.0.0.1:9081/plugins/functions/random2

###2217