kind: Deployment
apiVersion: apps/v1
metadata:
  name: kmanager
  namespace: default
  labels:
    app: kmanager
spec:
  selector:
    matchLabels:
      app: kmanager
  template:
    metadata:
      labels:
        app: kmanager
    spec:
      nodeName: cloud-node
      hostNetwork: true
      containers:
        - name: kmanager
          image: emqx/ekuiper-manager:1.3.1
          ports:
            - containerPort: 9082
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: kmanager-http
  namespace: default
spec:
  type: NodePort
  selector:
    app: kmanager
  ports:
    - nodePort: 32555
      port: 9082
      targetPort: 9082