apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ekuiper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ekuiper.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ekuiper.fullname" . }}-headless
  replicas: 1
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: ekuiper-data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "ekuiper.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
    - metadata:
        name: ekuiper-plugins
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "ekuiper.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ekuiper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ekuiper.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ekuiper.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      volumes:
      - name: ekuiper-log
        emptyDir: {}
      {{- if not .Values.persistence.enabled }}
      - name: ekuiper-data
        emptyDir: {}
      - name: ekuiper-plugins
      {{- else if .Values.persistence.existingClaim }}
      - name: ekuiper-data
        persistentVolumeClaim:
        {{- with .Values.persistence.existingClaim }}
          claimName: {{ tpl . $ }}
        {{- end }}
      - name: ekuiper-plugins
        persistentVolumeClaim:
        {{- with .Values.persistence.existingClaim }}
          claimName: {{ tpl . $ }}
        {{- end }}
      {{- end }}
      - name: kuiper-config
        configMap:
          name: {{ include "ekuiper.fullname" . }}
          items:
          - key: kuiper.yaml
            path: kuiper.yaml
      {{- if .Values.tls.enabled }}
      - name: certs
        secret:
          secretName: {{ template "neuron.tlsSecretName" . }}
          items:
            - key: {{ ternary "tls.crt" "ca.crt" .Values.tls.existingSecretFullChain }}
              path: xyz-rootca.pem
            - key: tls.crt
              path: xyz-certificate.pem
            - key: tls.key
              path: xyz-private.pem.key
        {{- end }}
      containers:
        - name: ekuiper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.ekuiperEnv.enabled }}
          env:
          - name: {{ .Values.ekuiperEnv.key.mqttDefaultServer }}
            value: {{ .Values.ekuiperEnv.value.mqttDefaultServer }}
          {{- end }}
          command:
          - /bin/sh
          - -c
          - |
            mkdir -p /kuiper/plugins/functions /kuiper/plugins/portable /kuiper/plugins/sinks /kuiper/plugins/sources /kuiper/plugins/wasm
            /kuiper/bin/kuiperd
          readinessProbe:
            httpGet:
              {{- $restPort := index .Values "kuiperConfig" "kuiper.yaml" "basic" "restPort" }}
              port: {{ $restPort | default 9081 }}
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            {{- $restPort := index .Values "kuiperConfig" "kuiper.yaml" "basic" "restPort" }}
            - name: restapi
              containerPort: {{ $restPort | default 9081 }}
            {{- $port := index .Values "kuiperConfig" "kuiper.yaml" "basic" "port" }}
            - name: ekuiper
              containerPort: {{ $port | default 20498 }}
          volumeMounts:
          - name: ekuiper-log
            mountPath: "/kuiper/log"
          - name: ekuiper-data
            mountPath: "/kuiper/data"
          - name: ekuiper-plugins
            mountPath: "/kuiper/plugins"
          {{- if .Values.tls.enabled }}
          - name: certs
            mountPath: "/var/kuiper/xyz-rootca.pem"
            subPath: "xyz-rootca.pem"
            readOnly: true
          - name: certs
            mountPath: "/var/kuiper/xyz-certificate.pem"
            subPath: "xyz-certificate.pem"
            readOnly: true
          - name: certs
            mountPath: "/var/kuiper/xyz-private.pem.key"
            subPath: "xyz-private.pem.key"
            readOnly: true
          {{- end }}
          - name: kuiper-config
            mountPath: "/kuiper/etc/kuiper.yaml"
            subPath: "kuiper.yaml"
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}



