run:
  timeout: 10m
  skip-dirs:
    - internal/plugin
  build-tags:
    - edgex

linters:
  disable-all: true
  enable:
    - gofumpt
    - staticcheck
    - govet
    - gci

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/lf-edge/ekuiper)
  staticcheck:
    go: '1.20'
