run:
  skip-dirs:
    - internal/plugin

linters:
  disable-all: true
  enable:
    - gofumpt
    - staticcheck
    - govet
    - gci

linters-settings:
  gci:
    sections:
      - default
      - standard
      - prefix(github.com/lfedge/ekuiper)
  staticcheck:
    go: '1.20'
