# Copyright 2021 EMQ Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Keep in this version to avoid glibc version problem
FROM debian:bullseye

ARG GO_VERSION
ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBIAN_SNAPSHOT="20260831T000000Z"

## Bullseye reached EOL on 2026-08-31. Pin APT to its final snapshot so that
## package indexes and package files cannot get out of sync as mirrors retire it.
RUN printf '%s\n' \
        "deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT}/ bullseye main" \
        "deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT}/ bullseye-updates main" \
        "deb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/${DEBIAN_SNAPSHOT}/ bullseye-security main" \
        > /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y make cmake wget git curl procps zip libucl-dev zlib1g-dev \
        pkg-config libczmq-dev build-essential debhelper jq zip \
    && rm -rf /var/lib/apt/lists/*

RUN case $(dpkg --print-architecture) in \
        arm|armhf|armv7) \
            ARCH=armv6l \
        ;; \
        *) \
            ARCH=$(dpkg --print-architecture)\
        ;; \
    esac \
    && wget --no-verbose https://golang.org/dl/go$GO_VERSION.linux-$ARCH.tar.gz \
    && tar -C /usr/local -xzf go$GO_VERSION.linux-$ARCH.tar.gz

RUN if [ "$(dpkg --print-architecture)" = "amd64" ]; then \
        wget https://github.com/apple/foundationdb/releases/download/7.3.19/foundationdb-clients_7.3.19-1_amd64.deb \
        && dpkg -i foundationdb-clients_7.3.19-1_amd64.deb; \
    fi

ENV PATH=$PATH:/usr/local/go/bin

RUN wget --no-verbose https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-src.tar.xz -O - | tar -xvJC /usr/local \
   && cd /usr/local/upx-4.2.4-src && make all \
   && ln -s /usr/local/upx-4.2.4-src/src/upx.out /usr/bin/upx
