name: Python sdk

on:
  push:
    tags:
  pull_request:
  release:
    types:
      - published

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python3 -m pip install --user --upgrade setuptools wheel twine
      - working-directory: "sdk/python"
        run: python3 setup.py sdist bdist_wheel
      - env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      - run: python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps ekuiper
