name: Update plugins

on:
  workflow_dispatch:
  push:
    branches:
      - hotfix190

jobs:

  build-plugins:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        plugin:
          - sinks/influx2
        arch:
          - linux/amd64
          - linux/arm64
        os:
          - [debian, "slim"]
          - [alpine, "alpine"]
        golang:
          - 1.18.5
        exclude:
          - os: [ alpine,"alpine" ]
            plugin: functions/labelImage
          - os: [ alpine,"alpine" ]
            plugin: functions/tfLite
          - os: [alpine,"alpine"]
            plugin: sinks/tdengine

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v2
    - uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: build plugins
      run: |
        docker run -i --rm \
            -v $(pwd):/ekuiper \
            --workdir /ekuiper \
            --platform ${{ matrix.arch }} \
            ghcr.io/lf-edge/ekuiper/base:${{ matrix.golang }}-${{ matrix.os[0] }} \
            bash -euc "make ${{ matrix.plugin }}"


  release:
    runs-on: ubuntu-latest

    needs:
    - build-plugins

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v1
      with:
        name: plugins
        path: _plugins
    - name: upload packages to s3
      if: github.event_name == 'release'
      run: |
        version=1.9.0
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-west-2
        aws s3 cp --quiet --recursive ./_plugins s3://packages.emqx/kuiper-plugins/$version
        aws cloudfront create-invalidation --distribution-id E170YEULGLT8XB --paths "/kuiper/$version/*,/kuiper-plugins/$version/*"